Name: `Vishal Haswani`\
Reg. No: `19BCI0181`\
Faculty: `Sharmila Banu K.`

# Text Vectorization

In [3]:
from sklearn.feature_extraction.text import CountVectorizer

vect = CountVectorizer(binary = True)

In [4]:
corpus = ["NLP is awesome", "I want to start an NLP company", "Top unicorns use NLP"]

In [5]:
vect.fit(corpus)

CountVectorizer(binary=True)

In [6]:
vocab = vect.vocabulary_

In [7]:
for key in vocab.keys():
    print ("{}: {}".format(key, vocab[key]))

nlp: 4
is: 3
awesome: 1
want: 10
to: 6
start: 5
an: 0
company: 2
top: 7
unicorns: 8
use: 9


In [13]:
test_string_1 = "I have an awesome NLP Company worth an awesome billion"
print(vect.transform([test_string_1]), "\n\n")
print(vect.transform([test_string_1]).toarray())

  (0, 0)	1
  (0, 1)	1
  (0, 2)	1
  (0, 4)	1 


[[1 1 1 0 1 0 0 0 0 0 0]]


## Mesuring The difference between 2 statements

In [12]:
from sklearn.metrics.pairwise import cosine_similarity
sim = cosine_similarity(vect.transform(["ML is an elective subject now"]).toarray(), \
                        vect.transform(["NLP is an attractive career now"]).toarray())
print(sim)

[[0.81649658]]


In [14]:
vect.transform(["ML is an elective subject now"]).toarray()

array([[1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0]], dtype=int64)

In [15]:
vect.transform(["NLP is an attractive career now"]).toarray()

array([[1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0]], dtype=int64)

## Checking the Orignality of Barak Obama's speaches

### Scraping 2 to 3 speaches for using as corpus

In [71]:
from urllib import request

# Newest to Oldest
urls = ["http://obamaspeeches.com/P-Obama-Inaugural-Speech-Inauguration.htm",
        "http://obamaspeeches.com/E11-Barack-Obama-Election-Night-Victory-Speech-Grant-Park-Illinois-November-4-2008.htm",
        "http://obamaspeeches.com/E-Barack-Obama-Speech-Manassas-Virgina-Last-Rally-2008-Election.htm",
       ]

In [72]:
responses = [request.urlopen(url) for url in urls]

In [73]:
from bs4 import BeautifulSoup

soups = [BeautifulSoup(response.read(), 'html.parser') for response in responses]
print(soups[0])

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">

<html><!-- InstanceBegin template="/Templates/ObamaSpeechesTemplate.dwt" codeOutsideHTMLIsLocked="false" -->
<head>
<meta content="Over 100 speeches by Barack Obama. Constantly updated. Complete and full text of each speech." name="description"/>
<meta content="barack obama, speeches, barak, oboma" name="keywords"/>
<!-- InstanceBeginEditable name="doctitle" -->
<title>Barack Obama Inauguration Speech - Jan 20 Inaugural</title>
<!-- InstanceEndEditable -->
<meta content="text/html; charset=utf-8" http-equiv="Content-Type"/>
<!-- InstanceBeginEditable name="head" --><!-- InstanceEndEditable -->
<script language="JavaScript" type="text/JavaScript">
</script>
<script src="http://a.remarketstats.com/px/?c=1f5a08ecb0b8bde" type="text/javascript"></script>
</head>
<style type="text/css">
A:h1 { font-style: none; } 
A:link {text-decoration: none;color:white}
A:visited {text-decoration: none; color:white}
A:active {text-decoratio

In [89]:
# print(soups[0].html.table.tr.find_all('td')[3].table.tr.td.find_all('font')[3])
# paragraphs_in_speaches = [soup.html.table.tr.find_all('td')[3].table.tr.td.find_all('p') for soup in soups]
speaches = [soups[0].html.table.tr.find_all('td')[3].table.tr.td.find_all('font')[3].get_text(),
            soups[1].html.table.tr.find_all('td')[3].table.tr.td.get_text(),
            soups[2].html.table.tr.find_all('td')[3].table.tr.td.get_text()
           ]
print(speaches[1])


Election Night Victory Speech 
              Grant Park, Illinois
              November 4, 2008


If 
              there is anyone out there who still doubts that America is a place 
              where all things are possible; who still wonders if the dream of 
              our founders is alive in our time; who still questions the power 
              of our democracy, tonight is your answer.
It’s 
              the answer told by lines that stretched around schools and churches 
              in numbers this nation has never seen; by people who waited three 
              hours and four hours, many for the very first time in their lives, 
              because they believed that this time must be different; that their 
              voice could be that difference.
It’s 
              the answer spoken by young and old, rich and poor, Democrat and 
              Republican, black, white, Latino, Asian, Native American, gay, straight, 
              disabled and not disabled – Ame

In [97]:
raw_speaches = [re.sub('[ \n]+', ' ', speach) for speach in speaches]
print(raw_speaches[1])

 Election Night Victory Speech Grant Park, Illinois November 4, 2008 If there is anyone out there who still doubts that America is a place where all things are possible; who still wonders if the dream of our founders is alive in our time; who still questions the power of our democracy, tonight is your answer. It’s the answer told by lines that stretched around schools and churches in numbers this nation has never seen; by people who waited three hours and four hours, many for the very first time in their lives, because they believed that this time must be different; that their voice could be that difference. It’s the answer spoken by young and old, rich and poor, Democrat and Republican, black, white, Latino, Asian, Native American, gay, straight, disabled and not disabled – Americans who sent a message to the world that we have never been a collection of Red States and Blue States: we are, and always will be, the United States of America. It’s the answer that led those who have been t

### Vectorizing the 2 older speaches and checking the latest one

In [98]:
vect = CountVectorizer(binary = True)

test_data = raw_speaches[0]
corpus = raw_speaches[1:]

In [100]:
vect.fit(corpus)
vocab = vect.vocabulary_
for key in vocab.keys():
    print ("{}: {}".format(key, vocab[key]))

election: 274
night: 565
victory: 913
speech: 797
grant: 374
park: 612
illinois: 436
november: 573
2008: 3
if: 435
there: 857
is: 448
anyone: 42
out: 600
who: 944
still: 811
doubts: 255
that: 852
america: 33
place: 635
where: 941
all: 25
things: 861
are: 47
possible: 650
wonders: 961
the: 853
dream: 260
of: 578
our: 597
founders: 340
alive: 24
in: 440
time: 875
questions: 676
power: 652
democracy: 218
tonight: 883
your: 977
answer: 40
it: 450
told: 880
by: 128
lines: 487
stretched: 823
around: 51
schools: 739
and: 37
churches: 159
numbers: 574
this: 864
nation: 557
has: 396
never: 562
seen: 748
people: 625
waited: 920
three: 870
hours: 427
four: 341
many: 516
for: 333
very: 910
first: 327
their: 854
lives: 492
because: 74
they: 859
believed: 85
must: 554
be: 72
different: 235
voice: 915
could: 185
difference: 234
spoken: 800
young: 976
old: 584
rich: 713
poor: 648
democrat: 219
republican: 703
black: 98
white: 943
latino: 468
asian: 53
native: 559
american: 34
gay: 351
straight: 816
di

In [103]:
latest_speach_vector = vect.transform([test_data]).toarray()
print(latest_speach_vector)

[[0 0 0 0 0 0 0 0 0 1 0 1 1 0 0 1 1 0 0 1 1 1 0 0 0 1 1 1 0 1 1 1 0 1 1 1
  1 1 0 0 1 0 0 0 0 0 0 1 0 0 0 1 1 0 1 0 0 0 1 0 0 0 0 0 0 1 0 1 0 0 0 0
  1 0 1 0 1 1 1 1 0 0 0 0 0 0 0 0 0 0 1 0 0 1 0 0 0 1 0 0 1 0 0 0 0 0 1 0
  0 0 1 0 1 0 0 0 0 0 0 1 1 0 0 0 0 0 1 1 1 0 0 0 1 0 0 0 1 0 1 0 0 1 1 0
  1 0 0 0 0 1 1 1 0 0 0 0 1 1 0 0 1 0 0 0 0 0 0 0 0 0 1 0 0 1 0 0 0 1 0 0
  0 0 0 0 0 1 0 0 0 1 0 1 0 1 1 0 0 0 0 0 0 0 1 0 0 0 1 0 0 0 0 0 0 0 1 0
  1 0 0 0 0 0 0 0 0 1 0 0 1 0 1 1 0 0 0 0 1 0 0 0 0 0 0 0 0 1 0 1 0 1 0 1
  0 1 0 0 1 0 0 0 0 0 0 0 1 1 1 0 0 1 1 1 0 0 0 0 1 0 0 0 1 1 1 0 1 0 0 0
  0 0 1 0 1 0 0 1 0 0 0 1 0 0 0 0 0 1 1 0 0 1 1 1 0 0 0 0 0 0 0 0 0 0 1 1
  0 0 0 0 0 0 0 0 0 1 0 0 1 1 1 0 0 1 1 1 1 0 0 0 1 0 0 0 1 1 1 0 0 0 0 0
  1 0 0 1 0 0 0 1 0 0 1 0 0 0 0 1 1 0 1 1 0 0 0 0 0 0 0 0 1 1 0 0 0 1 0 1
  1 0 0 1 1 0 0 0 1 0 0 1 1 0 1 0 1 0 1 0 1 0 0 1 0 0 0 0 0 0 1 1 0 1 1 1
  1 0 1 1 0 1 1 0 1 1 0 0 0 0 1 1 1 0 1 1 0 1 0 1 1 0 1 0 0 0 1 0 0 1 1 0
  0 0 0 0 0 0 1 1 1 1 0 1 0 0 0 1 0 0 

In [110]:
import numpy as np
import math
x = np.array(latest_speach_vector)

MIN = 0
MAX = math.sqrt(len(x[0]))
print(f"The value ranges from {MIN} to {MAX}, Higher the value the lesser is the vocabuary change")
print("Result:", np.linalg.norm(x))

The value ranges from 0 to 31.272991542223778, Higher the value the lesser is the vocabuary change
Result: 18.24828759089466


<center><h1>Thank You</h1></center>